### ISSUE TITLE
there is no preprocess function in repe/dump_features.py

### ISSUE THREAD

**Issue by pandaupc** [lancopku/clip-openness#2]

**Comment by RenShuhuai-Andy** [comment]
Hi, 
what kind os preprocess function do you want? There are functions of [dump_image_features](https://github.com/lancopku/clip-openness/blob/main/repe/dump_features.py#L147) and [dump_pretrained_text_features](https://github.com/lancopku/clip-openness/blob/main/repe/dump_features.py#L190) in `dump_features.py`
